name: igor_app
description: Aplicativo suporte para jogos de RPG

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth:
  cloud_firestore:
  firebase_core:
  firebase_storage:
  rxdart:
  dash:
  toast: ^0.1.3
  d20:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.1.3
  dash_generator:
  intl: ^0.15.8

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Fira-sans
      fonts:
        - asset: assets/fonts/FiraSans-Regular.otf

  assets:
    - assets/log_in/Igor.webp
    - assets/log_in/Google.webp
    - assets/log_in/Backgrownd.webp

    - assets/adventures/Coast.webp
    - assets/adventures/Corvali.webp
    - assets/adventures/Heartlands.webp
    - assets/adventures/Krevast.webp
    - assets/adventures/Padrão.webp
    - assets/adventures/barra_de_progressão_jogadas.webp
    - assets/adventures/marcador_barra_de_progressão.webp
    - assets/adventures/Botão_Criar_Nova_Aventura.webp
    - assets/adventures/andamento.webp
    - assets/adventures/jogadores.webp
    - assets/adventures/botão_adicionar_jogadores.webp
    - assets/adventures/botão_adicionar_sessões.webp
    - assets/adventures/espadas.webp
    - assets/adventures/botão_espadas.webp

    - assets/navbar/Aventuras.webp
    - assets/navbar/Configurações.webp
    - assets/navbar/Conta.webp
    - assets/navbar/Livros.webp
    - assets/navbar/Notificações.webp

    - assets/players/p1.webp
    - assets/players/p2.webp
    - assets/players/p3.webp
    - assets/players/p4.webp
    - assets/players/p5.webp
    - assets/players/p6.webp
    - assets/players/p7.webp
    - assets/players/p8.webp

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
